allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true

strictDepBuilds: true
optimisticRepeatInstall: true
verifyDepsBeforeRun: install
dedupePeerDependents: true

minimumReleaseAgeExclude:
  - vite@8.2.0
  - '@napi-rs/wasm-runtime@1.2.1'
  - occt-wasm@3.8.2
  - '@types/three@0.185.3'
  - three-mesh-bvh@0.9.14
